apiVersion: v1
kind: Namespace
metadata:
  name: operator
  annotations:
    iam.amazonaws.com/permitted: ".*"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: assume-role-operator
  namespace: operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: assume-role-operator-role
rules:
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - update
- apiGroups:
  - "*"
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - aws.chatwork
  resources:
  - "*"
  verbs:
  - "*"
---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: assume-role-operator-role-binding
subjects:
  - kind: ServiceAccount
    name: assume-role-operator
    namespace: operator
roleRef:
  kind: ClusterRole
  name: assume-role-operator-role
  apiGroup: rbac.authorization.k8s.io
