awsRoleArn: "arn:aws:iam::XXXXXXXX:role/assume-role-operator_role"
image:
   repository: "cwsakamoto/assume-role-operator"
   tag: "latest"
   imagePullPolicy: "Always"
deployment:
  replicas: 1

namespace:
  create: true

rbac:
  create: true
