{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: "{{ template "assume-role-operator.fullname" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
  name: {{ template "assume-role-operator.fullname" .}}
rules:
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - update
- apiGroups:
  - "*"
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - aws.chatwork
  resources:
  - "*"
  verbs:
  - "*"
{{- end -}}
